const images = [
    {
        id: 1,
        src: '/wolexy/john.jpg',
        alt: 'John',
        category: 'weddings',
    },
    {
        id: 2,
        src: '/wolexy/qudus 1 (1).jpg',
        alt: 'Qudus',
        category: 'social',
      },
      {
        id: 3,
        src: '/wolexy/ife (1).jpg',
        alt: 'Ife',
        category: 'social',
      },
      {
        id: 4,
        src: '/wolexy/sharon 2.jpg',
        alt: 'Sharon',
        category: 'outdoor',
      },
      {
        id: 5,
        src: '/wolexy/daniel abe.jpg',
        alt: 'Daniel Abe',
        category: 'outdoor',
      },
      {
        id: 6,
        src: '/wolexy/david 4.jpg',
        alt: 'Mr Dave',
        category: 'outdoor',
      },
      {
        id: 7,
        src: '/wolexy/gem 2.jpg',
        alt: 'Gem 2',
        category: 'social',
      },
      {
        id: 8,
        src: '/wolexy/gem 6.jpg',
        alt: 'Gem 3',
        category: 'social',
      },
      {
        id: 9,
        src: '/wolexy/TDA 7.jpg',
        alt: 'Gem4',
        category: 'weddings',
      },
      {
        id: 10,
        src: '/wolexy/wolexyImage5.JPG',
        alt: 'Gem5',
        category: 'weddings',
      },
      {
        id: 11,
        src: '/wolexy/wolexyImage3.jpg',
        alt: 'Gem6',
        category: 'outdoor',
      },
      {
        id: 12,
        src: '/wolexy/wolexyImage4.jpg',
        alt: 'Gem7',
        category: 'weddings',
      },
      {
        id: 13,
        src: '/wolexy/4.jpg',
        alt: 'Fashionista',
        category: 'social',
      },
      {
        id: 14,
        src: '/wolexy/wolexyImage7.JPG',
        alt: 'Gem7',
        category: 'weddings',
      },
      {
        id: 15,
        src: '/wolexy/2.jpg',
        alt: 'Fashionista Boy',
        category: 'social',
      },
      {
        id: 16,
        src: '/wolexy/1.jpg',
        alt: 'wolexy image1',
        category: 'weddings',
      },
      {
        id: 17,
        src: '/wolexy/3 (1).jpg',
        alt: 'Wolexy image2',
        category: 'outdoor',
      },
      {
        id: 18,
        src: '/wolexy/3 (2).jpg',
        alt: 'Wolexy image3',
        category: 'social',
      },
      {
        id: 19,
        src: '/wolexy/3.jpg',
        alt: 'Wolexy image4',
        category: 'weddings',
      },
      {
        id: 20,
        src: '/wolexy/5.jpg',
        alt: 'Wolexy image5',
        category: 'outdoor',
      },
      {
        id: 21,
        src: '/wolexy/7.jpg',
        alt: 'Wolexy image6',
        category: 'social',
      },
      {
        id: 22,
        src: '/wolexy/ayo 1.jpg',
        alt: 'Wolexy image7',
        category: 'weddings',
      },
      {
        id: 23,
        src: '/wolexy/ayo 2.jpg',
        alt: 'Wolexy image8',
        category: 'outdoor',
      },
      {
        id: 24,
        src: '/wolexy/bob 1.jpg',
        alt: 'Wolexy image9',
        category: 'social',
      },
      {
        id: 25,
        src: '/wolexy/bob 3 (1).jpg',
        alt: 'Wolexy image10',
        category: 'outdoor',
      },
      {
        id: 26,
        src: '/wolexy/bob 3 (2).jpg',
        alt: 'Wolexy image11',
        category: 'social',
      },
      {
        id: 27,
        src: '/wolexy/bob 3 (3).jpg',
        alt: 'Wolexy image12',
        category: 'social',
      },
      {
        id: 28,
        src: '/wolexy/bob 3 (4).jpg',
        alt: 'Wolexy image13',
        category: 'outdoor',
      },
      {
        id: 29,
        src: '/wolexy/bob 4.jpg',
        alt: 'Wolexy image14',
        category: 'social',
      },
      {
        id: 30,
        src: '/wolexy/bob clint 3.jpg',
        alt: 'Wolexy image15',
        category: 'outdoor',
      },
      {
        id: 31,
        src: '/wolexy/Bob clint 3.jpg',
        alt: 'Wolexy image16',
        category: 'social',
      },
      {
        id: 32,
        src: '/wolexy/bob clinton 4.jpg',
        alt: 'Wolexy image17',
        category: 'outdoor',
      },
      {
        id: 33,
        src: '/wolexy/bob clinton 10.jpg',
        alt: 'Wolexy image18',
        category: 'social',
      },
      {
        id: 34,
        src: '/wolexy/bob clinton 11.jpg',
        alt: 'Wolexy image19',
        category: 'outdoor',
      },
      {
        id: 35,
        src: '/wolexy/bob clinton 12.jpg',
        alt: 'Wolexy image20',
        category: 'social',
      },
      {
        id: 36,
        src: '/wolexy/bob clinton 14.jpg',
        alt: 'Wolexy image21',
        category: 'social',
      },
      {
        id: 37,
        src: '/wolexy/daddy (1).jpg',
        alt: 'Wolexy image22',
        category: 'social',
      },
      {
        id: 38,
        src: '/wolexy/daddy (1).jpg',
        alt: 'Wolexy image23',
        category: 'outdoor',
      },
      {
        id: 39,
        src: '/wolexy/daddy 3.jpg',
        alt: 'Wolexy image24',
        category: 'social',
      },
      {
        id: 40,
        src: '/wolexy/daddy.jpg',
        alt: 'Wolexy image25',
        category: 'outdoor',
      },
]
export default images;